# **Download dataset Housing price: https://drive.google.com/file/d/1qeJqFtRdjjHqExbWJcgKy0yJbczTTAE3/view**

In [ ]:
!gdown 1qeJqFtRdjjHqExbWJcgKy0yJbczTTAE3

Downloading...
From: https://drive.google.com/uc?id=1qeJqFtRdjjHqExbWJcgKy0yJbczTTAE3
To: /content/Housing.csv
100% 30.0k/30.0k [00:00<00:00, 54.3MB/s]

# **Import Libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Read dataset

In [ ]:
dataset_path = './Housing.csv'
df = pd.read_csv(dataset_path)
df

        price  area  bedrooms  ...  parking  prefarea furnishingstatus
0    13300000  7420         4  ...        2       yes        furnished
1    12250000  8960         4  ...        3        no        furnished
2    12250000  9960         3  ...        2       yes   semi-furnished
3    12215000  7500         4  ...        3       yes        furnished
4    11410000  7420         4  ...        2        no        furnished
..        ...   ...       ...  ...      ...       ...              ...
540   1820000  3000         2  ...        2        no      unfurnished
541   1767150  2400         3  ...        0        no   semi-furnished
542   1750000  3620         2  ...        0        no      unfurnished
543   1750000  2910         3  ...        0        no        furnished
544   1750000  3850         3  ...        0        no      unfurnished

[545 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

# Preprocessing Categorical

In [ ]:
# Check các cột có kiểu object
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)

['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']

In [ ]:
ordinal_encoder = OrdinalEncoder()
encoded_categorical_cols = ordinal_encoder.fit_transform(
    df[categorical_cols]
)
encoded_categorical_df = pd.DataFrame(
    encoded_categorical_cols,
    columns = categorical_cols
)
numerical_df = df.drop(categorical_cols, axis = 1)
encoded_df = pd.concat(
    [numerical_df, encoded_categorical_df], axis = 1
)
encoded_df

        price  area  bedrooms  ...  airconditioning  prefarea  furnishingstatus
0    13300000  7420         4  ...              1.0       1.0               0.0
1    12250000  8960         4  ...              1.0       0.0               0.0
2    12250000  9960         3  ...              0.0       1.0               1.0
3    12215000  7500         4  ...              1.0       1.0               0.0
4    11410000  7420         4  ...              1.0       0.0               0.0
..        ...   ...       ...  ...              ...       ...               ...
540   1820000  3000         2  ...              0.0       0.0               2.0
541   1767150  2400         3  ...              0.0       0.0               1.0
542   1750000  3620         2  ...              0.0       0.0               2.0
543   1750000  2910         3  ...              0.0       0.0               0.0
544   1750000  3850         3  ...              0.0       0.0               2.0

[545 rows x 13 columns]

# **Normalizing data**

In [ ]:
normalizer = StandardScaler()
dataset_arr = normalizer.fit_transform(encoded_df)
dataset_arr

array([[ 4.56636513,  1.04672629,  1.40341936, ...,  1.4726183 ,
         1.80494113, -1.40628573],
       [ 4.00448405,  1.75700953,  1.40341936, ...,  1.4726183 ,
        -0.55403469, -1.40628573],
       [ 4.00448405,  2.21823241,  0.04727831, ..., -0.67906259,
         1.80494113, -0.09166185],
       ...,
       [-1.61432675, -0.70592066, -1.30886273, ..., -0.67906259,
        -0.55403469,  1.22296203],
       [-1.61432675, -1.03338891,  0.04727831, ..., -0.67906259,
        -0.55403469, -1.40628573],
       [-1.61432675, -0.5998394 ,  0.04727831, ..., -0.67906259,
        -0.55403469,  1.22296203]])

# **Split X, y**

In [ ]:
X, y = dataset_arr[:, 1:], dataset_arr[:, 0]

# **Split train, val, test**

In [ ]:
test_size = 0.3
random_state = 1
is_shuffle = True
X_train, X_val, y_train, y_val = train_test_split(
    X,  y,
    test_size=test_size,
    shuffle=is_shuffle,
    random_state=random_state
)

# **Train model and Evaluate**

## **Decision Tree**

In [ ]:
regressor_dt = DecisionTreeRegressor(
    random_state=random_state
)
regressor_dt.fit(X_train, y_train)

DecisionTreeRegressor(random_state=1)

In [ ]:
y_pred = regressor_dt.predict(X_val)

mae = mean_absolute_error(y_val, y_pred)
mse = mean_squared_error(y_val, y_pred)
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")

Mean Absolute Error: 0.594233095728814
Mean Squared Error: 0.7245255619360014

## **Random Forest**

In [ ]:
regressor_rf = RandomForestRegressor(
    random_state=random_state
)
regressor_rf.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [ ]:
y_pred = regressor_rf.predict(X_val)

mae = mean_absolute_error(y_val, y_pred)
mse = mean_squared_error(y_val, y_pred)
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")

Mean Absolute Error: 0.46093873321571177
Mean Squared Error: 0.37944418523089524

# **AdaBoost**

In [ ]:
regressor_ada = AdaBoostRegressor(
    random_state=random_state
)
regressor_ada.fit(X_train, y_train)

AdaBoostRegressor(random_state=1)

In [ ]:
y_pred = regressor_ada.predict(X_val)

mae = mean_absolute_error(y_val, y_pred)
mse = mean_squared_error(y_val, y_pred)
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")

Mean Absolute Error: 0.567680019897059
Mean Squared Error: 0.5739244030038942

## **Gradient Boost**

In [ ]:
regressor_gb = GradientBoostingRegressor(
    random_state=random_state
)
regressor_gb.fit(X_train, y_train)

GradientBoostingRegressor(random_state=1)

In [ ]:
y_pred = regressor_gb.predict(X_val)

mae = mean_absolute_error(y_val, y_pred)
mse = mean_squared_error(y_val, y_pred)
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")

Mean Absolute Error: 0.4516626127750995
Mean Squared Error: 0.39610445936979427