# **(XGBoost Regressor) Dự đoán khu vực bị cháy rừng qua dataset : https://drive.google.com/file/d/1xwJmYJxEia06sxUdJyGO7JFx4DNK1fbp/view**

In [ ]:
!gdown 1xwJmYJxEia06sxUdJyGO7JFx4DNK1fbp

Downloading...
From: https://drive.google.com/uc?id=1xwJmYJxEia06sxUdJyGO7JFx4DNK1fbp
To: /content/Problem3.csv
100% 37.4k/37.4k [00:00<00:00, 69.4MB/s]

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
data = pd.read_csv("/content/Problem3.csv")
data

     X  Y month  day      FFMC  ...  temp  RH  wind   rain      area
0    7  5   mar  fri  4.468204  ...   8.2  51   6.7  False  0.000000
1    7  4   oct  tue  4.517431  ...  18.0  33   0.9  False  0.000000
2    7  4   oct  sat  4.517431  ...  14.6  33   1.3  False  0.000000
3    8  6   mar  fri  4.529368  ...   8.3  97   4.0   True  0.000000
4    8  6   mar  sun  4.503137  ...  11.4  99   1.8  False  0.000000
..  .. ..   ...  ...       ...  ...   ...  ..   ...    ...       ...
505  4  3   aug  sun  4.414010  ...  27.8  32   2.7  False  2.006871
506  2  4   aug  sun  4.414010  ...  21.9  71   5.8  False  4.012592
507  7  4   aug  sun  4.414010  ...  21.2  70   6.7  False  2.498152
508  1  4   aug  sat  4.558079  ...  25.6  42   4.0  False  0.000000
509  6  3   nov  tue  4.388257  ...  11.8  31   4.5  False  0.000000

[510 rows x 13 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       510 non-null    int64
 1   Y       510 non-null    int64
 2   month   510 non-null    object
 3   day     510 non-null    object
 4   FFMC    510 non-null    float64
 5   DMC     510 non-null    float64
 6   DC      510 non-null    float64
 7   ISI     510 non-null    float64
 8   temp    510 non-null    float64
 9   RH      510 non-null    int64
 10  wind    510 non-null    float64
 11  rain    510 non-null    bool
 12  area    510 non-null    float64
dtypes: bool(1), float64(7), int64(3), object(2)
memory usage: 48.4+ KB

In [ ]:
categorical_cols = data.select_dtypes(include=['object', 'bool']).columns.tolist()

ordinal_encoder = OrdinalEncoder()
encoded_categorical_cols = ordinal_encoder.fit_transform(data[categorical_cols])

encoded_categorical_df = pd.DataFrame(
    encoded_categorical_cols,
    columns=categorical_cols
)

numerical_df = data.drop(categorical_cols, axis = 1)
encoded_df = pd.concat([numerical_df, encoded_categorical_df], axis = 1)
encoded_df

     X  Y      FFMC    DMC     DC  ...  wind      area  month  day  rain
0    7  5  4.468204   26.2   94.3  ...   6.7  0.000000    7.0  0.0   0.0
1    7  4  4.517431   35.4  669.1  ...   0.9  0.000000   10.0  5.0   0.0
2    7  4  4.517431   43.7  686.9  ...   1.3  0.000000   10.0  2.0   0.0
3    8  6  4.529368   33.3   77.5  ...   4.0  0.000000    7.0  0.0   1.0
4    8  6  4.503137   51.3  102.2  ...   1.8  0.000000    7.0  3.0   0.0
..  .. ..       ...    ...    ...  ...   ...       ...    ...  ...   ...
505  4  3  4.414010   56.7  665.6  ...   2.7  2.006871    1.0  3.0   0.0
506  2  4  4.414010   56.7  665.6  ...   5.8  4.012592    1.0  3.0   0.0
507  7  4  4.414010   56.7  665.6  ...   6.7  2.498152    1.0  3.0   0.0
508  1  4  4.558079  146.0  614.7  ...   4.0  0.000000    1.0  2.0   0.0
509  6  3  4.388257    3.0  106.7  ...   4.5  0.000000    9.0  5.0   0.0

[510 rows x 13 columns]

In [ ]:
X = encoded_df.drop(columns=['area'])
y = encoded_df['area']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.3,
    random_state = 7
)

In [ ]:
xg_reg = xgb.XGBRegressor(
    n_estimators=102,
    learning_rate=0.01,
    max_depth=3,
    seed=7
)

xg_reg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=102,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
preds = xg_reg.predict(X_test)

mae = mean_absolute_error(y_test, preds)
mse = mean_squared_error(y_test, preds)

print ("Evaluation results on test set:")
print (f"Mean Absolute Error : {mae}")
print (f"Mean Squared Error : {mse}")

Evaluation results on test set:
Mean Absolute Error : 1.1484401341167767
Mean Squared Error : 1.8845074196256495

# **(XGBoost Classifier) Dự đoán chất lương rựu nằm trong 3 class, dataset: https://drive.google.com/file/d/1pVdH-2b_odeuEPdXbLQYDcHXxgqqBK4i/view**

In [ ]:
!gdown 1pVdH-2b_odeuEPdXbLQYDcHXxgqqBK4i

Downloading...
From: https://drive.google.com/uc?id=1pVdH-2b_odeuEPdXbLQYDcHXxgqqBK4i
To: /content/Problem4.csv
100% 12.3k/12.3k [00:00<00:00, 23.2MB/s]

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("/content/Problem4.csv")
df

     alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  Target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[178 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  Target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [ ]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.3,
    random_state = 7
)

In [ ]:
xg_class = xgb.XGBClassifier(seed=7)

xg_class.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
preds = xg_class.predict(X_test)

In [ ]:
train_acc = accuracy_score(y_train, xg_class.predict(X_train))
test_acc = accuracy_score(y_test, preds)

print(f"Train ACC: {train_acc}")
print(f"Test ACC: {test_acc}")

Train ACC: 1.0
Test ACC: 1.0