# **1. Data Frame**

## **Create a data frame**

In [3]:
import pandas as pd

df = pd.read_csv('/content/advertising_simple.csv')
print(df)

df_t = df.T
print(df_t)

    TV  Radio  Newspaper  Sales
0   44     39         45     10
1   17     45         69     12
2  151     41         58     16
3  180     10         58     17
4    8     48         75      7
5   57     32         23     11
6  120     19         11     13
7    8      2          1      4
            0   1    2    3   4   5    6  7
TV         44  17  151  180   8  57  120  8
Radio      39  45   41   10  48  32   19  2
Newspaper  45  69   58   58  75  23   11  1
Sales      10  12   16   17   7  11   13  4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         8 non-null      int64
 1   Radio      8 non-null      int64
 2   Newspaper  8 non-null      int64
 3   Sales      8 non-null      int64
dtypes: int64(4)
memory usage: 388.0 bytes

In [5]:
df.describe()

               TV      Radio  Newspaper      Sales
count    8.000000   8.000000   8.000000   8.000000
mean    73.125000  29.500000  42.500000  11.250000
std     68.059716  17.146428  27.619869   4.334249
min      8.000000   2.000000   1.000000   4.000000
25%     14.750000  16.750000  20.000000   9.250000
50%     50.500000  35.500000  51.500000  11.500000
75%    127.750000  42.000000  60.750000  13.750000
max    180.000000  48.000000  75.000000  17.000000

## **Sorting**

In [48]:
df = pd.read_csv('/content/advertising_simple.csv')
df.sort_values('Sales')

    TV  Radio  Newspaper  Sales
7    8      2          1      4
4    8     48         75      7
0   44     39         45     10
5   57     32         23     11
1   17     45         69     12
6  120     19         11     13
2  151     41         58     16
3  180     10         58     17

In [49]:
df.sort_values(['Newspaper', 'Sales'])

    TV  Radio  Newspaper  Sales
7    8      2          1      4
6  120     19         11     13
5   57     32         23     11
0   44     39         45     10
2  151     41         58     16
3  180     10         58     17
1   17     45         69     12
4    8     48         75      7

## **Add a column**

In [50]:
df['ID'] = list(range(2, 10))
df

    TV  Radio  Newspaper  Sales  ID
0   44     39         45     10   2
1   17     45         69     12   3
2  151     41         58     16   4
3  180     10         58     17   5
4    8     48         75      7   6
5   57     32         23     11   7
6  120     19         11     13   8
7    8      2          1      4   9

In [51]:
df = df.set_index('ID')
df

     TV  Radio  Newspaper  Sales
ID
2    44     39         45     10
3    17     45         69     12
4   151     41         58     16
5   180     10         58     17
6     8     48         75      7
7    57     32         23     11
8   120     19         11     13
9     8      2          1      4

In [52]:
df.index

Index([2, 3, 4, 5, 6, 7, 8, 9], dtype='int64', name='ID')

In [53]:
df = df.reset_index(drop=True, inplace=False)
df

    TV  Radio  Newspaper  Sales
0   44     39         45     10
1   17     45         69     12
2  151     41         58     16
3  180     10         58     17
4    8     48         75      7
5   57     32         23     11
6  120     19         11     13
7    8      2          1      4

## **loc and iloc**
loc: for indexing by labes

iloc: for indexing by positional index

In [59]:
df = pd.read_csv('/content/advertising_simple.csv')
df.set_index([['A', 'B', 'C', 'D',
              'F', 'G', 'H', 'I']],
             inplace=True)
df

    TV  Radio  Newspaper  Sales
A   44     39         45     10
B   17     45         69     12
C  151     41         58     16
D  180     10         58     17
F    8     48         75      7
G   57     32         23     11
H  120     19         11     13
I    8      2          1      4

In [60]:
df.loc['C', 'Radio']

np.int64(41)

In [61]:
df.iloc[2, 1]

np.int64(41)

## **Select Values**

In [65]:
# select radio from df
df['Radio']

A    39
B    45
C    41
D    10
F    48
G    32
H    19
I     2
Name: Radio, dtype: int64

In [63]:
# select * from df where Newspaper < 30
df.loc[df['Newspaper'] < 30]

    TV  Radio  Newspaper  Sales
G   57     32         23     11
H  120     19         11     13
I    8      2          1      4

In [64]:
# select * from df where Sale > 10
df.loc[df['Sales'] > 10]

    TV  Radio  Newspaper  Sales
B   17     45         69     12
C  151     41         58     16
D  180     10         58     17
G   57     32         23     11
H  120     19         11     13

In [66]:
# select * from df where Sale > 10 and Newspaper < 30
df.loc[(df['Sales'] > 10) & (df['Newspaper'] < 30)]

    TV  Radio  Newspaper  Sales
G   57     32         23     11
H  120     19         11     13

## **Concatenate data**

In [70]:
import pandas as pd

# Create the first DataFrame (df1)
data1 = {'col1': [1, 2], 'col2': [3, 4]}
df1 = pd.DataFrame(data1)
print("DataFrame 1:")
print(df1)

# Create the second DataFrame (df2)
data2 = {'col1': [5, 6], 'col2': [7, 8]}
df2 = pd.DataFrame(data2)
print("\nDataFrame 2:")
print(df2)

# Concatenate the two DataFrames
df3 = pd.concat([df1, df2])
df4 = df3.reset_index(drop=True)
print(df4)

DataFrame 1:
   col1  col2
0     1     3
1     2     4

DataFrame 2:
   col1  col2
0     5     7
1     6     8
   col1  col2
0     1     3
1     2     4
2     5     7
3     6     8

In [71]:
df3 = pd.concat([df1, df2], ignore_index=True)
df3

   col1  col2
0     1     3
1     2     4
2     5     7
3     6     8

# **Convert categories to numbers**

In [72]:
import pandas as pd

df = pd.read_csv('/content/weatherHistory_simple.csv')
df

  Precip Type  Temperature (C)
0        rain             12.2
1        rain             13.8
2        rain             14.7
3        rain             13.8
4        rain             12.7
5        rain              0.5
6        snow             -0.4
7        snow             -1.1
8        snow             -1.6
9        snow             -2.1

In [73]:
df['Precip Type'] = pd.Categorical(df['Precip Type']).codes
df

   Precip Type  Temperature (C)
0            0             12.2
1            0             13.8
2            0             14.7
3            0             13.8
4            0             12.7
5            0              0.5
6            1             -0.4
7            1             -1.1
8            1             -1.6
9            1             -2.1

# **2. Example 1**

In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/WeatherHistory2D.csv')
df.head(10)

                  Formatted Date  Temperature (C)
0  2006-01-01 00:00:00.000 +0100         0.577778
1  2006-01-01 01:00:00.000 +0100         1.161111
2  2006-01-01 02:00:00.000 +0100         1.666667
3  2006-01-01 03:00:00.000 +0100         1.711111
4  2006-01-01 04:00:00.000 +0100         1.183333
5  2006-01-01 05:00:00.000 +0100         1.205556
6  2006-01-01 06:00:00.000 +0100         2.222222
7  2006-01-01 07:00:00.000 +0100         2.072222
8  2006-01-01 08:00:00.000 +0100         2.200000
9  2006-01-01 09:00:00.000 +0100         2.733333

## **Date time**

In [13]:
datetime = pd.to_datetime('2006-12-01 00:00:00.000 +0700', utc = True)
print(datetime)
print(datetime.year)
print(datetime.month)
print(datetime.day)
print(datetime.hour)
print(datetime.minute)
print(datetime.second)
print(datetime.tz)

2006-11-30 17:00:00+00:00
2006
11
30
17
0
0
UTC

In [14]:
datetime = pd.to_datetime('2006-12-01 00:00:00.000', utc = False)
print(datetime)
print(datetime.year)
print(datetime.month)
print(datetime.day)
print(datetime.hour)
print(datetime.minute)
print(datetime.second)

2006-12-01 00:00:00
2006
12
1
0
0
0

In [15]:
print(pd.Timestamp(year=2006, month=3, day=29, hour=1, minute=35, second=10))
print(pd.Timestamp('2006-03-29 01:35:10'))
print(pd.Timestamp('Sep 04, 1982 1:35:18'))

2006-03-29 01:35:10
2006-03-29 01:35:10
1982-09-04 01:35:18

In [16]:
df = pd.read_csv('/content/WeatherHistory2D.csv')
df['Formatted Date'] = pd.to_datetime(df['Formatted Date'], utc=True)

df['year'] = df['Formatted Date'].dt.year
df['month'] = df['Formatted Date'].dt.month
df['day'] = df['Formatted Date'].dt.day
df['hour'] = df['Formatted Date'].dt.hour
df.drop('Formatted Date', axis = 1, inplace=True)
df

       Temperature (C)  year  month  day  hour
0             0.577778  2005     12   31    23
1             1.161111  2006      1    1     0
2             1.666667  2006      1    1     1
3             1.711111  2006      1    1     2
4             1.183333  2006      1    1     3
...                ...   ...    ...  ...   ...
96448         0.488889  2016     12   31    18
96449         0.072222  2016     12   31    19
96450        -0.233333  2016     12   31    20
96451        -0.472222  2016     12   31    21
96452        -0.677778  2016     12   31    22

[96453 rows x 5 columns]

# **Example 2**

Tweets dataset

In [22]:
import pandas as pd

df = pd.read_csv('train.csv')
df.head(10)

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
5,8,NaN,NaN,#RockyFire Update => California Hwy. 20 closed...,1
6,10,NaN,NaN,#flood #disaster Heavy rain causes flash flood...,1
7,13,NaN,NaN,I'm on top of the hill and I can see a fire in...,1
8,14,NaN,NaN,There's an emergency evacuation happening now ...,1
9,15,NaN,NaN,I'm afraid that the tornado is coming to our a...,1

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [24]:
df.drop(['id', 'keyword', 'location'],
        axis=1,
        inplace=True)

In [25]:
df

                                                   text  target
0     Our Deeds are the Reason of this #earthquake M...       1
1                Forest fire near La Ronge Sask. Canada       1
2     All residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     Just got sent this photo from Ruby #Alaska as ...       1
...                                                 ...     ...
7608  Two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @TheTawniest The out of control w...       1
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1
7611  Police investigating after an e-bike collided ...       1
7612  The Latest: More Homes Razed by Northern Calif...       1

[7613 rows x 2 columns]

In [29]:
df.loc[2:5, 'text']

2    All residents asked to 'shelter in place' are ...
3    13,000 people receive #wildfires evacuation or...
4    Just got sent this photo from Ruby #Alaska as ...
5    #RockyFire Update => California Hwy. 20 closed...
Name: text, dtype: object

# **WeatherHistory simple**

In [31]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/weatherHistory_simple.csv')
df

  Precip Type  Temperature (C)
0        rain             12.2
1        rain             13.8
2        rain             14.7
3        rain             13.8
4        rain             12.7
5        rain              0.5
6        snow             -0.4
7        snow             -1.1
8        snow             -1.6
9        snow             -2.1

In [33]:
df.groupby('Precip Type').mean()

             Temperature (C)
Precip Type
rain               11.283333
snow               -1.300000

In [38]:
df['Temperature (F)'] = df['Temperature (C)'] * 9/5 + 32
df

  Precip Type  Temperature (C)  Temperature (F)
0        rain             12.2            53.96
1        rain             13.8            56.84
2        rain             14.7            58.46
3        rain             13.8            56.84
4        rain             12.7            54.86
5        rain              0.5            32.90
6        snow             -0.4            31.28
7        snow             -1.1            30.02
8        snow             -1.6            29.12
9        snow             -2.1            28.22

# **Example 3**

Credit Card Fraud Detection

In [40]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/creditcard.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [42]:
df.groupby('Class').size()

Class
0    284315
1       492
dtype: int64